### PR TITLE
TMAG Carrier Board Prototype

### PR DESCRIPTION
**Pull request by Brendanofawesome**
### TMAG Carrier Board Prototype
Some mechanical team members were asking about the dimensions of our TMAG rotation sensors to incorporate into their designs. As such, I made these boards that (hopefully) match the final mechanical dimensions, although electrical connections are subject to change.

I am mainly looking for a quick review before I send the dimensions off to mechanical :).

Features:
- 5V TVS diode protects ICs
- LED connected to the 3.3V line
- An on-off switch can be added if needed

There are two boards in this branch:
1. A miniaturized 2-sided board designed to fit anywhere. [KiCanvas](https://kicanvas.org/?github=https://github.com/SJSURoboticsTeam/urc-electrical-2026/blob/TMAG_Carrier/TMAG_Carrier/Miniaturized/MiniatureTMAG_Carrier.kicad_pro)
2. A 1-sided board that is slightly larger, but does not come with z-height mounting considerations. [KiCanvas](https://kicanvas.org/?github=https://github.com/SJSURoboticsTeam/urc-electrical-2026/blob/TMAG_Carrier/TMAG_Carrier/Normal%20Size/TMAG_Carrier.kicad_pro)
image
image

### CODE REVIEW

**Comment by DolphinGui** [comment]
I am currently in an airport and will do further review later, but one quick thing: you can put the i2c onto the 4pin connector. We'll be color-coding and labeling this stuff anyways, so the exact pinout can vary.

**Comment by DolphinGui** [comment]
also it might be more convenient for mechanical if the holes are an even distance away from the edge i.e. 2.5mm or 1mm.

**Comment by DolphinGui** [comment]
You should also label the individual pin types with SDA, SCL, etc.

**Comment by Brendanofawesome** [comment]
I made the holes 2.5mm away from the board edge. They are 10mm apart from each other for ease of mounting. I added labels to the pins and set them to be knockout so we can add Sharpie later if needed. How does it look?
image

**Comment by DolphinGui** [comment]
lgtm, just add order numbers from digikey

**Comment by Brendanofawesome** [comment]
> lgtm, just add order numbers from digikey

I've added part numbers and links, however, I'm not sure if what I did is exactly what you mean.... let me know :)

**Review by DolphinGui — APPROVED** [review]
lgtm

**Review by DolphinGui — APPROVED** [review]
fixed merge error

**Pull request merged**
